[package]
name = "leap-seconds"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.13", features = ["blocking"] }
flate2 = { version = "1.0.24" }
sha1 = { version = "0.10.5" }
tar = { version = "0.4.38" }
thiserror = { version = "1.0.37", default-features = false }
