name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: cargo test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [ubuntu-stable, ubuntu-beta, macos, windows]
        include:
        - build: ubuntu-stable
          os: ubuntu-latest
          rust: stable
        - build: ubuntu-beta
          os: ubuntu-latest
          rust: beta
        - build: macos
          os: macos-latest
          rust: stable
        - build: windows
          os: windows-latest
          rust: stable
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with: 
          toolchain: ${{ matrix.rust }}
      - run: cargo test --verbose
      
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt
    - run: cargo fmt --check
    
  rustdoc:
    name: rustdoc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - run: cargo doc --verbose
    
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy
    - run: cargo clippy --verbose
